app = "diacritical"

kill_signal = "SIGTERM"
kill_timeout = 5

[[services]]
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "1s"
    interval = "15s"
    method = "get"
    path = "/hello"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"

    [services.http_checks.headers]
      X-Forwarded-Host = "example.com"
      X-Forwarded-Port = "4001"
      X-Forwarded-Proto = "https"

[[services.ports]]
  force_https = true
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443
